### ISSUE TITLE
fetch request for tmdb

### ISSUE THREAD

**Issue by hcweigand10** [BUButtercup/Project1#5]
- [x] accepts query parameter from dropdown menu in search bar
- [x] manipulates the request URL with the proper parameters
- [x] assign variables for all relevant attributes (director/genre/release year/etc)
- [x] limit results to 5
- [x] sort by top imdb score

**Comment by sinka27** [comment]
1. Accepts query parameter from user input and dropdown menu for the genre.
2. Sort by popularity and vote counts.
3. Limit results to 5
